"use client";

import { useMutation, useQuery } from "@tanstack/react-query";
import { Check, Circle, Loader2, ArrowLeft, Send } from "lucide-react";
import { getPublishPreview, publishJob, type PublishPreview } from "@/features/jobs/api/publish";

export function PublishJobPage({ orgId, jobId }: { orgId: string; jobId: string }) {
  const previewQuery = useQuery({ queryKey: ["job-publish-preview", orgId, jobId], queryFn: () => getPublishPreview(orgId, jobId), staleTime: 30_000 });
  const publishMutation = useMutation({ mutationFn: () => publishJob(orgId, jobId), onSuccess: () => previewQuery.refetch() });

  if (previewQuery.isLoading) return <StateMessage label="Opening the publish desk" />;
  if (previewQuery.isError) return <StateMessage label={previewQuery.error.message || "This job could not be loaded."} error />;
  const preview = previewQuery.data?.preview;
  if (!preview) return <StateMessage label="Job preview unavailable." error />;

  if (preview.status === "PUBLISHED" || publishMutation.isSuccess) {
    return <StateMessage label="This role is public. The hiring standard is now live." success />;
  }

  return <main className="min-h-svh bg-paper text-ink lg:grid lg:grid-cols-[4.5rem_minmax(0,1fr)]"><Rail /><div className="min-w-0"><header className="sticky top-0 z-20 border-b border-forest/12 bg-paper/95 px-6 py-6 backdrop-blur md:px-10 lg:px-14"><div className="mx-auto flex max-w-7xl items-center justify-between"><span className="font-mono text-sm uppercase tracking-[0.18em] text-forest">Trace · Publish desk</span><span className="font-mono text-sm uppercase tracking-[0.14em] text-olive">Draft review</span></div></header><div className="mx-auto max-w-7xl px-6 pb-32 md:px-10 lg:px-14"><section className="border-b border-forest/12 py-16"><p className="font-mono text-sm uppercase tracking-[0.18em] text-olive">Ready for the public</p><div className="mt-5 flex flex-wrap items-end justify-between gap-8"><div><h1 className="max-w-[16ch] text-5xl font-light leading-[.95] tracking-[-.045em] md:text-6xl">{preview.title}</h1><p className="mt-5 text-xl text-olive">{preview.role_category_name ?? "Role definition"}{preview.department ? ` · ${preview.department}` : ""}</p></div><div className="border-l border-forest/25 pl-5 font-mono text-sm uppercase tracking-[.13em] text-olive">{preview.open_positions ?? 1} position{preview.open_positions === 1 ? "" : "s"}<br />{preview.work_mode ?? "Work mode not set"}</div></div><p className="mt-10 max-w-[65ch] text-lg leading-relaxed text-moss">{preview.description || "No role description was provided."}</p></section><PreviewSections preview={preview} /><footer className="mt-20 flex flex-wrap items-center justify-between gap-6 border-t border-forest pt-7"><button type="button" onClick={() => history.back()} className="inline-flex items-center gap-2 text-base text-olive hover:text-forest"><ArrowLeft className="size-4" /> Back to job</button><button type="button" disabled={publishMutation.isPending} onClick={() => publishMutation.mutate()} className="inline-flex items-center gap-3 bg-forest px-6 py-4 font-mono text-sm uppercase tracking-[.14em] text-paper hover:bg-moss disabled:opacity-50">{publishMutation.isPending ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />} Publish role</button></footer>{publishMutation.isError && <p className="mt-4 text-right text-sm text-destructive">{publishMutation.error.message}</p>}</div></div></main>;
}

function PreviewSections({ preview }: { preview: PublishPreview }) { return <div className="mt-16 grid gap-16 lg:grid-cols-2"><PreviewSection title="Eligibility" items={Object.entries(preview.eligibility).filter(([, value]) => value !== null && value !== undefined)} /><PreviewSection title="Application requirements" items={Object.entries(preview.submission_requirements).filter(([, value]) => value !== null && value !== undefined)} /><ListSection title="Technical bar" items={preview.requirements.map((item) => `${item.priority_type} · ${item.name} (${item.requirement_type.toLowerCase()})`)} /><ListSection title="Evaluation priorities" items={preview.evaluation_priorities.map((item) => `${item.name} · ${item.weight}%`)} /><ListSection title="Evidence priorities" items={preview.evidence_priorities.map((item) => `${item.name} · ${item.weight}%`)} /><ListSection title="Success signals" items={preview.success_signals.map((item) => `${item.name} · ${item.weight}%`)} /></div>; }
function PreviewSection({ title, items }: { title: string; items: [string, unknown][] }) { return <section><SectionHeading title={title} /><dl className="mt-5 divide-y divide-forest/10">{items.map(([key, value]) => <div key={key} className="flex justify-between gap-6 py-3 text-sm"><dt className="text-olive">{key.replaceAll("_", " ")}</dt><dd className="text-right text-ink">{String(value)}</dd></div>)}</dl></section>; }
function ListSection({ title, items }: { title: string; items: string[] }) { return <section><SectionHeading title={title} /><ul className="mt-5 divide-y divide-forest/10">{items.length ? items.map((item) => <li key={item} className="py-3 text-base text-ink">{item}</li>) : <li className="py-3 text-olive">Not configured</li>}</ul></section>; }
function SectionHeading({ title }: { title: string }) { return <h2 className="border-b border-forest/12 pb-4 font-mono text-sm uppercase tracking-[.16em] text-forest">{title}</h2>; }
function Rail() { return <aside className="hidden border-r border-forest/12 bg-warm lg:flex lg:flex-col lg:items-center lg:py-6"><span className="grid size-8 place-items-center border border-forest/30 font-mono text-xs text-forest">T</span><div className="mt-24 flex flex-1 flex-col items-center gap-4"><span className="font-mono text-xs text-forest">PUBLISH</span><span className="h-16 w-px bg-forest" /><Circle className="size-3 fill-sage text-sage" /></div></aside>; }
function StateMessage({ label, error, success }: { label: string; error?: boolean; success?: boolean }) { return <main className="grid min-h-svh place-items-center bg-paper px-6 text-center"><div><div className={`mx-auto grid size-12 place-items-center border ${error ? "border-destructive text-destructive" : "border-forest text-forest"}`}>{success ? <Check className="size-5" /> : error ? "!" : <Loader2 className="size-5 animate-spin" />}</div><p className="mt-6 font-mono text-sm uppercase tracking-[.16em] text-olive">{label}</p></div></main>; }
