import { cn } from "@/lib/utils";
import { EmptyPanel, PanelHead } from "./primitives";
import type { ActivityItem, AttentionItem, ClosedJob, DraftJob, Health, InterviewGroup, JobRow } from "./org-mock";

const HEALTH_TONE: Record<Health, string> = { healthy: "text-forest", review: "text-destructive", context: "text-olive" };
const HEALTH_LABEL: Record<Health, string> = { healthy: "Healthy", review: "Needs review", context: "Context needs review" };

export function ActiveJobs({ jobs = [] }: { jobs?: JobRow[] }) {
  return <section aria-labelledby="active-jobs"><PanelHead label="Active hiring" count={jobs.length} />{jobs.length === 0 ? <div className="mt-8"><EmptyPanel>No active jobs yet. Created jobs will appear here with their hiring progression.</EmptyPanel></div> : <div className="mt-8 border-t border-forest/12"><div className="label-index hidden grid-cols-12 gap-6 py-3 text-olive lg:grid"><span className="col-span-4">Job</span><span className="col-span-5">Applications → eligible → evaluating → ready → interviews</span><span className="col-span-2">Signal</span><span className="col-span-1 text-right">Closes</span></div><ul>{jobs.map((job) => <li key={job.id} className="border-t border-forest/10"><div className="group grid gap-4 py-6 lg:grid-cols-12 lg:items-center lg:gap-6"><div className="lg:col-span-4"><p className="text-lg tracking-[-0.02em] text-ink">{job.title}</p><p className="label-index mt-1.5 text-olive">{job.status}</p></div><div className="lg:col-span-5"><Progression job={job} /></div><div className="lg:col-span-2"><p className={cn("flex items-baseline gap-2 text-sm", HEALTH_TONE[job.health])}><span aria-hidden>●</span>{HEALTH_LABEL[job.health]}</p><p className="mt-1 max-w-[28ch] text-xs leading-relaxed text-moss">{job.healthNote}</p></div><div className="flex items-baseline justify-between gap-4 lg:col-span-1 lg:justify-end"><span className="label-index text-olive">{job.closes}</span><span aria-hidden className="text-forest">→</span></div></div></li>)}</ul></div>}</section>;
}

function Progression({ job }: { job: JobRow }) {
  return <ol className="flex flex-wrap items-baseline gap-x-3 gap-y-2">{[{ value: job.applications, label: "applications" }, { value: job.eligible, label: "eligible" }, { value: job.evaluating, label: "evaluating" }, { value: job.ready, label: "ready" }, { value: job.interviews, label: "interviews" }].map((step, i, all) => <li key={step.label} className="flex items-baseline gap-3"><span className="flex items-baseline gap-1.5"><span className={cn("font-mono text-xl tabular-nums", i === all.length - 1 ? "text-forest" : step.value === 0 ? "text-olive" : "text-ink")}>{step.value}</span><span className="label-index text-olive">{step.label}</span></span>{i < all.length - 1 && <span aria-hidden className="text-forest/30">→</span>}</li>)}</ol>;
}

export function NeedsAttention({ items = [] }: { items?: AttentionItem[] }) {
  return <section><PanelHead label="Needs your attention" count={items.length} />{items.length === 0 ? <div className="mt-8"><EmptyPanel>Nothing needs attention right now. New review items will appear here.</EmptyPanel></div> : <ul className="mt-8 divide-y divide-forest/10 border-y border-forest/12">{items.map((item) => <li key={item.jobId} className="grid gap-2 py-5 md:grid-cols-[16rem_1fr_auto] md:items-baseline md:gap-6"><span className="text-base text-ink">{item.job}</span><span className={cn("text-sm", item.tone === "conflict" ? "text-destructive" : item.tone === "gap" ? "text-olive" : "text-forest")}>{item.detail}</span><span className="label-index text-forest">{item.action} →</span></li>)}</ul>}</section>;
}

export function UpcomingInterviews({ groups = [] }: { groups?: InterviewGroup[] }) {
  return <section><PanelHead label="Upcoming interviews" count={groups.reduce((sum, group) => sum + group.items.length, 0)} />{groups.length === 0 ? <div className="mt-8"><EmptyPanel>No upcoming interviews yet. Scheduled interviews will appear here.</EmptyPanel></div> : <div className="mt-8 space-y-8">{groups.map((group) => <div key={group.day}><p className="label-index text-olive">{group.day}</p><ul className="mt-3 divide-y divide-forest/10 border-t border-forest/12">{group.items.map((item) => <li key={`${group.day}-${item.time}`} className="grid gap-1 py-4 md:grid-cols-[4.5rem_1fr_auto] md:items-baseline md:gap-6"><span className="font-mono text-sm tabular-nums text-forest">{item.time}</span><span className="text-sm text-ink">{item.who}<span className="text-olive"> · {item.job}</span><span className="block text-xs text-moss">{item.kind}</span></span><span className="label-index text-forest">View →</span></li>)}</ul></div>)}</div>}</section>;
}

export function DraftJobs({ drafts = [] }: { drafts?: DraftJob[] }) {
  return <section><PanelHead label="Draft jobs" count={drafts.length} />{drafts.length === 0 ? <div className="mt-8"><EmptyPanel>No draft jobs yet. In-progress hiring definitions will appear here.</EmptyPanel></div> : <ul className="mt-8 grid gap-6 md:grid-cols-2">{drafts.map((draft) => <li key={draft.id} className="border border-forest/15 bg-warm p-6"><div className="flex items-baseline justify-between gap-4"><p className="text-lg tracking-[-0.02em] text-ink">{draft.title}</p><span className="font-mono text-sm tabular-nums text-olive">{draft.configured}%</span></div><div aria-hidden className="mt-3 h-1 bg-forest/10"><div className="h-full bg-forest" style={{ width: `${draft.configured}%` }} /></div><p className="label-index mt-5 text-olive">Missing</p><ul className="mt-2 space-y-1">{draft.missing.map((missing) => <li key={missing} className="flex items-baseline gap-2 text-sm text-moss"><span aria-hidden className="text-destructive">•</span>{missing}</li>)}</ul>{draft.imported && <p className="mt-5 border-l-2 border-olive/50 pl-3 text-xs leading-relaxed text-olive">Imported from public JD — needs organization confirmation</p>}<span className="label-index mt-6 inline-flex items-center gap-2 text-forest">Continue setup →</span></li>)}</ul>}</section>;
}

export function RecentActivity({ items = [] }: { items?: ActivityItem[] }) {
  return <section><PanelHead label="Recent activity" />{items.length === 0 ? <div className="mt-8"><EmptyPanel>No activity yet. Hiring events will appear here.</EmptyPanel></div> : <ul className="mt-8 divide-y divide-forest/10 border-y border-forest/12">{items.map((item) => <li key={`${item.when}-${item.what}`} className="grid gap-1 py-4 md:grid-cols-[7rem_1fr] md:items-baseline md:gap-6"><span className="label-index text-olive">{item.when}</span><span className="text-sm text-ink">{item.what}<span className="block text-xs text-moss">{item.where}</span></span></li>)}</ul>}</section>;
}

export function RecentlyClosed({ jobs = [] }: { jobs?: ClosedJob[] }) {
  return <section><PanelHead label="Recently closed" />{jobs.length === 0 ? <div className="mt-8"><EmptyPanel>No closed jobs yet. Completed hiring processes will appear here.</EmptyPanel></div> : <ul className="mt-8 border-t border-forest/12">{jobs.map((job) => <li key={job.id} className="grid gap-2 border-b border-forest/10 py-5 md:grid-cols-[16rem_1fr_auto] md:items-baseline md:gap-6"><span className="text-base text-ink">{job.title}</span><span className="text-sm text-moss">{job.line}</span><span className="label-index text-olive">{job.closed}</span></li>)}</ul>}</section>;
}
