name: Build and deploy Node.js app to Azure Web App - trace

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build API
        run: npm run build --workspace=apps/api

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-api
          path: |
            apps/api/dist
            apps/api/package.json
            package.json
            package-lock.json
            packages/shared

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-api

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: E686901CD7704B339C11FE3F927066FE
          tenant-id: 5CF0511EC92D4DEA90074FD477DC5869
          subscription-id: 57D854DA63F34AB2A10692D51F08F6FB

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "trace"
          slot-name: "Production"
          package: .
